export const SET_INPUT_MESSAGE_TEXT = 'SET_INPUT_MESSAGE_TEXT';
export const SET_CHAT_LIST = 'SET_CHAT_LIST';

export const SET_DATA_ROWS = 'SET_DATA_ROWS'
export const SET_INDEXES='SET_INDEXES'
export const SET_ROW_PLACE_VALUE = 'SET_ROW_PLACE_VALUE'

export const SET_PRICELIST_HEADER_DETAILS = 'SET_PRICELIST_HEADER_DETAILS'

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SET_PRICELIST_HEADER_DETAILS_STATUS = 'SET_PRICELIST_HEADER_DETAILS_STATUS'



